name: Build and Deploy Markdown with GFM

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install cmark-gfm
        run: |
          sudo apt-get update
          sudo apt-get install -y cmark-gfm

      - name: Convert Markdown to HTML
        run: |
          mkdir out
          for f in *.md; do
            name=$(basename "$f" .md)
            cmark-gfm "$f" > "out/$name.html"
          done

      - name: Setup NodeJS
      - uses: actions/setup-node@v3
      
      - name: Install Node Modules
        run: npm install --include=dev

      - name: Download jq
        run: |
          sudo apt-get install jq

      - name: Deploy to GitHub pages
        run: |
          npx gh-pages -d dist -u "${GITHUB_ACTOR} <oskar.codes@gmail.com>" -m "Deployment: '$(jq -r .head_commit.message < "$GITHUB_EVENT_PATH")'"
