name: Build and Deploy Markdown with GFM

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install cmark-gfm
        run: |
          sudo apt-get update
          sudo apt-get install -y cmark-gfm

      - name: Make build.sh executable
        run: chmod +x ./build.sh
        
      - name: Run build file
        run: ./build.sh
        shell: bash

      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
